<?php   require_once './templates/header.phtml'; 
        $isLoggin = UserHelper::checkSession();
        $isAdmin = UserHelper::verify();
?>

    <main class="categories-main">
        <div class="categories-filter">
            <form class="addCategory-form" action="addCategory" method="POST">
                <input class="input-category"type="text" name="newCategory" placeholder="Ingrese la categoria...">
                <button class="input-submit-category">+</button>
            </form>
            <div class="categories-container-checkbox">
                <?php foreach($categories as $category) {
                    ?>
                    <div class="checkbox-box">
                        <div class="checkbox-delete">
                            <button class="button-delete-category"><a href="delCategory/<?= $category->id_category?>"><i class="fa-solid fa-x"></i></a></button>
                            <p><?= $category->category ?></p>
                        </div>
                        <form action="updateCategory/<?php echo $category->id_category ?>" method="POST">
                            <button class="button-update-category"><i class="fa-solid fa-pen-to-square"></i></button>
                            <input type="text" name="categoryName" placeholder="<?php echo $category->category ?>">
                            <?php if (isset($_GET['error'])) {
                            echo '<p class="error-message">' . ($_GET['error']) . '</p>';
                            } ?>
                        </form>
                    </div>
                <?php } ?>
                </div>
        </div>
    </main>

<?php require_once 'templates/footer.phtml';?>