
<!DOCTYPE html>
<html>
<head>
    <title>Error 404 - Página no encontrada</title>
    <link rel="stylesheet" href="/TP-Especial-UNICEN-master/css/style.css">
</head>
<body>
    <main class="main-error">
        <h1 class="error-title">404</h1>
        <p class="error-text-1">Página no encontrada</p>
        <p class="error-text">Lo sentimos, la página que estás buscando no se encuentra en este servidor.</p>
        <!-- Puedes incluir contenido adicional o enlaces aquí -->
    </main>
</body>
</html>




