<?php 
    require_once './app/helper/UserHelper.php';
    $isLoggin = UserHelper::checkSession();
    $isAdmin = UserHelper::verify();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <base href="'.BASE_URL.'">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TecnoMundo</title>
    <link rel="stylesheet" href="/TP-Especial-UNICEN-master/css/style.css">
    <link rel="stylesheet" href="/TP-Especial-UNICEN-master/css/carrusel.css">
    
</head>
<body>
<header class="grid-header">
        <div class="container-logo">
            <a href="productos" class="container-logo">
                <img src="/TP-Especial-UNICEN-master/img/logo.png" alt="logo" class="logo">
                <h1 class="logo-text">TecnoMundo</h1>
            </a>
        </div>
        <div class="container-search-bar">
            <input type="text" class="search-bar" placeholder="Buscar...">
        </div>
</header>

<nav class="grid-nav nav-bar">
        <ul class="nav-list-main">
            <li><a href="<?php echo BASE_URL; ?>" class="index-home">Inicio</a></li>
            <li><a href=" <?php echo URL_PRODUCT; ?>" class="index-products nav-text">Productos</a></li>

            <?php if($isAdmin=='administrador'){ ?>
                <!-- <li><a href="usuarios" class="index-contact nav-text">Usuarios</a></li> -->
                <li><a href="<?php echo URL_CATEGORIES; ?>" class="index-contact nav-text">Categorias</a></li>
            <?php } ?>
            <?php 
                if($isLoggin){?>
                    <li class="index-user nav-text">Bienvenido <span class="user-name"><?php echo $_SESSION['usuario'] ?></span></li>
                    <li><a href="<?php echo URL_LOGOUT;?>" class="index-logout nav-text">Cerrar Sesion</a></li>
               <?php } else{
                ?>
                    <li><a href="<?php echo URL_LOGIN;?>" class="index-contact nav-text">Login/Register</a></li>
                <?php 
                }
            ?>
        </ul>
        <i class="fa-solid fa-bars button-var"></i>
        <ul class="nav-list hide-menu">
            <li><a href="" class="index-home">Inicio</a></li>
            <li><a href=" <?php echo URL_PRODUCT; ?>" class="index-products nav-text">Productos</a></li>
            <li><a href="<?php echo URL_LOGIN;?>" class="index-contact nav-text">Login/Register</a></li>
        </ul>
</nav>