<?php require_once 'templates/header.phtml'; ?>

    

  <section id="container-slider">	
   <a href="javascript: funcionEjecutar('anterior');" class="arrowPrev"><i class="fas fa-chevron-circle-left"></i></a>
   <a href="javascript: funcionEjecutar('siguiente');" class="arrowNext"><i class="fas fa-chevron-circle-right"></i></a>
   <ul class="listslider">
     <li><a itlist="itList_0" href="#" class="item-select-slid"></a></li>
     <li><a itlist="itList_1" href="#"></a></li>
     <li><a itlist="itList_2" href="#"></a></li>
   </ul>
   <ul id="slider">
     <li style="background-image: url('imagenes/01.jpg'); z-index:0; opacity: 1;">
       <div class="content_slider" >
         <div>
           <h2> <img src="/TP-Especial-UNICEN/img/shoes.jpg" alt=""> </h2>
	   <p>Escribe el texto que aparecerá sobre la imagen número 1.</p>
	   <a href="<?php echo BASE_URL; ?>productos" class="btnSlider">Acceder</a>
	 </div>
       </div>
     </li>
     <li style="background-image: url('imagenes/02.jpg'); ">
       <div class="content_slider" >
         <div>
           <h2>Imagen 2</h2>
	   <p>Escribe el texto que aparecerá sobre la imagen número 2</p>
	   <a href="<?php echo BASE_URL; ?>productos" class="btnSlider">Acceder</a>
	 </div>
       </div>
     </li>
     <li style="background-image: url('imagenes/03.jpg'); ">
       <div class="content_slider" >
         <div>
           <h2>Imagen 3</h2>
	   <p>Escribe el texto que aparecerá sobre la imagen número 3</p>
	   <a href="<?php echo BASE_URL; ?>productos" class="btnSlider">Acceder</a>
	 </div>
       </div>
     </li>
  </ul>
</section>
  
<?php   require_once 'templates/footer.phtml'; ?>

