<?php require_once 'templates/header.phtml'; ?>

<main>

  <section id="container-slider">	
   <a href="javascript: funcionEjecutar('anterior');" class="arrowPrev"><i class="fas fa-chevron-circle-left"></i></a>
   <a href="javascript: funcionEjecutar('siguiente');" class="arrowNext"><i class="fas fa-chevron-circle-right"></i></a>
   <ul class="listslider">
     <li><a itlist="itList_0" href="#" class="item-select-slid"></a></li>
     <li><a itlist="itList_1" href="#"></a></li>
     <li><a itlist="itList_2" href="#"></a></li>
   </ul>
   <ul id="slider">
    <li style="background-image: url('/TP-Especial-UNICEN-master/img/banner.png'); z-index:0; opacity: 1;">
      <div class="content_slider" >
        <div>
          <h2>LOS MEJORES PRODUCTOS ACA</h2>
          <p>Haz click en acceder para comenzar </p>
          <a href="<?php echo BASE_URL; ?>productos" class="btnSlider">Ver mas</a>
        </div>
      </div>
    </li>
    <li style="background-image: url('/TP-Especial-UNICEN-master/img/banner1.png'); ">
      <div class="content_slider" >
        <div>
          <h2>APROVECHA LAS OFERTAS</h2>
          <p>Hasta 20% de descuento en cada producto</p>
          <a href="<?php echo BASE_URL; ?>productos" class="btnSlider">Ver mas</a>
        </div>
      </div>
    </li>
    <li style="background-image: url('/TP-Especial-UNICEN-master/img/banner2.png'); ">
      <div class="content_slider" >
        <div>
          <h2>100% SEGURO</h2>
          <p>Podes verificar las reseñas de nuestros clientes</p>
          <a href="<?php echo BASE_URL; ?>productos" class="btnSlider">Ver mas</a>
        </div>  
      </div>
    </li>
  </ul>
  </section>
</main>

  
<?php   require_once 'templates/footer.phtml'; ?>

