<?php require_once './templates/header.phtml'; ?>
<main class="grid-main-contact">
    <div class="container-form">
        <div class="container-back">
            <div class="container-back-login">
                <h3>¿Ya tienes una cuenta?</h3>
                <p>Inicia sesion para entrar en la pagina</p>
                <button id="button-sing-in">Iniciar Sesion</button>
            </div>
            <div class="container-back-register">
                <h3>¿Aun no tienes una cuenta?</h3>
                <p>Registrate ahora!</p>
                <button id="button-sing-up">Registrarse</button>
            </div>
        </div>
        <div class="container-login-register">
            <form action="iniciarSesion" class="form-login" method="POST">
                <h2>Iniciar Sesion</h2>
                <input type="text" name ="user" placeholder="Nombre de usuario">
                <input type="password" name ="password" placeholder="Contraseña">
                <?php
                    if (isset($_GET['error'])) {
                        echo '<p class="error-message">' . ($_GET['error']) . '</p>';
                    }
                ?>
                <button type="submit">Iniciar Sesion</button>
            </form>
            <form action="addUser" class="form-register ocultar" method="POST">
                <h2>Registrarse</h2>
                <input type="text" name ="fullname" placeholder="Nombre completo" required>
                <input type="text" name ="user" placeholder="Usuario" required minlength="5">
                <input type="email" name ="email" placeholder="Correo electronico" required>
                <input type="password" name ="password" placeholder="Contraseña" required>
                <?php
                    if (isset($_GET['error'])) {
                        echo '<p class="error-message">' . ($_GET['error']) . '</p>';
                    }
                ?>
                <button type="submit">Registrarse</button>
            </form>
        </div>
    </div>
</main>

<?php require_once 'templates/footer.phtml';?>