<?php
    require_once 'templates/header.phtml';
    require_once './app/helper/UserHelper.php';
    $isLoggin = UserHelper::checkSession();
    $isAdmin = UserHelper::verify(); ?>


<main class="grid-main-products">
    <aside class="categories-filter">
        <form class="categories-container-checkbox" action="filterCategories" method="POST">
                <select name="selectCategory" id="">
                <?php foreach($categories as $category) {?>
                    <option value="<?php echo $category->id_category?>"><?= $category->category ?></option>
                <?php } ?>
                </select>
                <input class="input-submit-filter" type="submit" value="Filtrar">
        </form>
        <?php if($isAdmin == 'administrador'){ ?>
        <div class="form-products">
            <form action="addProduct" method="post" enctype="multipart/form-data">
                <label>Producto</label>
                <input class="" name="name" type="text" maxlength="50">
                <label>Categoria</label>
                <select name="category" id="">
                    <?php foreach($categories as $category) {?>
                        <option value="<?php echo $category->id_category?>"><?php echo $category->category ?></option> 
                    <?php } ?>
                </select>
                <label>Descripcion</label>
                <input class="" name="description" type="text" maxlength="255">
                <label>Precio</label>
                <input class="" name="price" type="number" maxlength="50">
                <label>Imagen</label>
                <input type="file" name="img" placeholder="Inserte link de la imagen">
                <?php
                    if (isset($_GET['error'])) {
                        echo '<p class="error-message">' . ($_GET['error']) . '</p>';
                    }
                ?>
                <button type="submit">ENVIAR</button>
            </form>
        </div>
        <?php } ?>
    </aside>
    <div class="categories-container">
        <?php foreach($products as $product) {?>
            
            <div class="container-product">
                <div class="container-img">
                    <img src="<?php echo $product->img ?>" alt="">
                </div>
                <div class="container-description">
                    <div class="data-container">
                        <p class="product-price">$ <?php echo $product->price ?></p>
                        <p class="product-name"><?php echo $product->name ?></p>
                        <p class="product-category">Categoria: <?php echo $product->category?></p>
                        <p class="product-description"><?php echo substr($product->description,0,20)?>...</p>
                    </div>
                    <div class="buttons-container">
                        <?php if($isAdmin == 'administrador'){ ?>
                        <button class="delButton"><a href="delProduct/<?php echo $product->id_product?>">BORRAR</a></button>
                        <?php } ?>
                        <div class="form-edit-products posicion ocultar">
                                <form action="editar/<?php echo $product->id_product?>" method="POST" enctype="multipart/form-data">
                                    <div>
                                        <label>Producto</label>
                                        <input class="" name="name" type="text" value="<?php echo $product->name ?>" maxlength="25">
                                    </div>
                                    <div>
                                        <label>Categoria</label>
                                        <select name="category" id="">
                                            <?php foreach($categories as $category) {?>
                                                <option value="<?php echo $category->id_category?>"><?php echo $category->category ?></option> 
                                            <?php } ?>
                                        </select>
                                    </div>
                                    <div>
                                        <label>Descripcion</label>
                                        <input class="" name="description" type="text" value="<?php echo $product->description ?>" maxlength="50">
                                    </div>
                                    <div>
                                        <label>Precio</label>
                                        <input class="" name="price" type="number" value="<?php echo $product->price ?>" maxlength="50">
                                    </div>
                                    <div>
                                        <label>Imagen</label>
                                        <input type="file" name="img" placeholder="Inserte link de la imagen" value="<?php echo $product->img?>">
                                    </div>
                                    <button type="submit">EDITAR</button>
                                </form>
                                <button class="cerrar">X</button>
                        </div>
                        <?php if($isAdmin == 'administrador'){ ?>                 
                        <button class="modify">EDITAR</button>
                        <?php } ?> 
                        <a href="producto/<?php echo $product->id_product?>" class="product-detail">Ver mas</a>  
                    </div>
                </div>
            </div>
        <?php }  ?>   
    </div>
</main>

<?php
    require_once 'templates/footer.phtml';

?>